#flow_id:
#    id: flow_id
#    steps:
#        state_name:
#            next: string
#            code: string
#            message:
#                text: string


greeting:
    id: greeting
    steps:
#        нужно добавлять этот фиктивный первый шаг. Иначе переключение будет работать некорректно
        idle:
            next: greet
        greet:
            message:
                text: Добрый день! Ответьте на несколько вопросов
            next: ask_name
        ask_name: # что означает переход на стейт? на нем отправляется сообщение. Но данные нужно собирать с предыдущего степа
            message:
                text: Как вас зовут?
            code: name
            next: ask_email
        ask_email:
            message:
                text: Ваш email
            code: email
            next: complete
        complete:
            message:
                text: Спасибо за инфу!
#            если нет next - это последний