#flow_id:
#    id: flow_id
#    steps:
#        state_name:
#            next: string
#            code: string
#            message:
#                text: string
#       action: string (required)

support:
    id: support
    steps:
        idle:
            action: send_message # а на idle точно нужен action?
            next: ask_category
        ask_category:
            message:
                text: Выберите категорию
                answers:
                    -   text: Биллинг
                    -   text: Настройка сервера
                    -   text: Доступы
            code: category
            next: ask_message
            action: collect_answer
        ask_message:
            message:
                text: Опишите проблему
            code: message
            next: complete
            action: collect_answer
        complete:
            message:
                text: |
                    Заявка отправлена. 
                    Ожидайте ответа на почту
            action: send_support_request

greeting:
    id: greeting
    steps:
        #        нужно добавлять этот фиктивный первый шаг. Иначе переключение будет работать некорректно
        idle:
            next: greet
            action: send_message
        greet:
            message:
                text: |
                    Добрый день! Чтобы лучше помочь вам, ответьте на несколько вопросов. 
                    Для начала поделитесь номером телефона
                answers:
                    -   text: Отправить номер
                        request_contact: true
            code: phone
            next: ask_name
            action: handle_phone
        ask_name: # что означает переход на стейт? на нем отправляется сообщение. Но данные нужно собирать с предыдущего степа
            message:
                text: Как вас зовут?
            code: name
            next: ask_status
            action: send_message
        ask_status:
            message:
                text: Ваш статус?
                answers:
                    -   text: Сегодня
                    -   text: Завтра
                    -   text: Послезавтра
            code: status
            next: ask_email
            action: collect_answer
        ask_email:
            message:
                text: Ваш email
            code: email
            next: complete
            action: collect_answer
        complete:
            message:
                text: '🆗 Ваши ответы помогут мне предоставить вам наиболее релевантную информацию и поддержку. Спасибо, что делитесь с нами! 💖'
            #            если нет next - это последний. На нем никаких code быть не должно - это закрывающее сообщение, от пользователя после него не ожидается никакого ввода
            action: send_onboard_form  # выполняется после отправки message. Такой порядок только для complete
